//infoconstants.ts
//
export const DATABASE_NAME:string = 'http://localhost:5984/geninfo';
export const PERSON_KEY: string = 'person';
export const ETUDIANTPERSON_KEY:string = 'etudperson';
export const DEPARTEMENTID_KEY: string = 'departementid';
export const ANNEEID_KEY: string = 'anneeid';
export const SEMESTREID_KEY: string = 'semestreid';
export const UNITEID_KEY: string = 'uniteid';
export const MATIEREID_KEY: string = 'matiereid';
export const GROUPEID_KEY: string = 'groupeid';
export const ENSEIGNANTID_KEY: string = 'enseignantid';
export const ETUDIANTID_KEY: string = 'etudiantid';
//
export const ROLE_SUPER: string = 'super';
export const ROLE_ADMIN: string = 'admin';
export const ROLE_PROF: string = 'prof';
export const ROLE_ETUD: string = 'etud';
export const SUPER_USERNAME: string = 'admin';
export const SUPER_LASTNAME: string = 'SYSTEM';
export const SUPER_FIRSTNAME: string = 'Administrator';
//
export const ANNEE_TYPE:string = 'annee';
export const ANNEE_PREFIX:string = 'ANN';
export const DEPARTEMENT_TYPE: string = 'departement';
export const DEPARTEMENT_PREFIX: string = 'DEP';
export const ENSEIGNANT_TYPE: string = 'enseignant';
export const ENSEIGNANT_PREFIX: string = 'PRF';
export const ETUDAFFECTATION_TYPE: string = 'etudaffectation';
export const ETUDAFFECTATION_PREFIX: string = 'ETF';
export const ETUDEVENT_TYPE: string = 'etudevent';
export const ETUDEVENT_PREFIX: string = 'EVT';
export const ETUDIANT_TYPE: string = 'etudiant';
export const ETUDIANT_PREFIX: string = 'ETD';
export const GROUPE_TYPE: string = 'groupe';
export const GROUPE_PREFIX: string = 'GRP';
export const MATIERE_TYPE: string = 'matiere';
export const MATIERE_PREFIX: string = 'MAT';
export const PERSON_PREFIX: string = 'PER';
export const PROFAFFECTATION_TYPE: string = 'profaffectation';
export const PROFAFFECTATION_PREFIX: string = 'AFP';
export const SEMESTRE_TYPE: string = 'semestre';
export const SEMESTRE_PREFIX: string = 'SEM';
export const UNITE_TYPE: string = 'unite';
export const UNITE_PREFIX: string = 'UNT';
export const GROUPEEVENT_TYPE: string = 'groupeevent';
export const GROUPEEVENT_PREFIX: string = 'GVT';
export const ADMINISTRATOR_TYPE: string = 'administrator';
export const ADMINISTRATOR_PREFIX: string = 'ADM';